name: Cobertura de teste e Build

on:
  push:
    branches:
      - main

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
    - name: Clona Repositorio
      uses: actions/checkout@v2

    - name: Configura .NET na VM
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x

    - name: Baixa dependencias dos projetos
      run: dotnet restore src/Gestor_Projetos_Tarefas.sln

    - name: Executa a compilacao
      run: dotnet build src/Gestor_Projetos_Tarefas.sln --configuration Release


    - name: Salvando dockerfile
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-api-dockerFile
        path: src/Gestor_Projetos_Tarefas.Api/Dockerfile

    - name: Salvando src
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-api-src
        path: src/


    - name: Salvando artefatos da compilacao api (bin)
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-api
        path: src/Gestor_Projetos_Tarefas.Api/bin/Release/net7.0

    - name: Salvando artefatos da compilacao testes
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-teste-build
        path: src/Gestor_Projetos_Tarefas.Api.Test/bin/Release/net7.0


  testar:
    runs-on: ubuntu-latest
    needs: compilar
    
    steps:

    - name: Clona Repositorio
      uses: actions/checkout@v2

    - name: Configura .NET na VM
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x

    - name: Baixando DockerFile
      uses: actions/download-artifact@v2
      with:
        name: artefatos-teste-build
        path: ./testes/
    
    - name: Baixando Artefatos
      uses: actions/download-artifact@v2
      with:
        name: artefatos-teste-build
        path: ./testes/

    - name: Executa testes
      run: dotnet test ./testes/Gestor_Projetos_Tarefas.Api.Test.dll --configuration Release --no-restore

  gerar_assets:
    needs: [compilar,testar]
    runs-on: ubuntu-latest

    steps:

    - name: Baixando Artefatos dockerfile
      uses: actions/download-artifact@v2
      with:
        name: artefatos-api-dockerFile
        path: ./dockerFile/

    - name: Baixando Artefatos
      uses: actions/download-artifact@v2
      with:
        name: artefatos-api-src
        path: ./deployed/src/

    - name: Construindo imagem Docker
      run: docker build -f ./dockerFile/Dockerfile -t gestorprojetostarefasapi:latest ./deployed/src --output ./deployed/image

    - name: Salvando imagem Docker nos artefatos
      uses: actions/upload-artifact@v2
      with:
        name: dockerImage
        path: ./deployed
        retention-days: 7