name: Cobertura de teste e Build

on:
  push:
    branches:
      - main

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
    - name: Clona Repositorio
      uses: actions/checkout@v2

    - name: Configura .NET na VM
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x

    - name: Baixa dependencias dos projetos
      run: dotnet restore

    - name: Executa a compilacao
      run: dotnet build --configuration Release

    - name: Criar diretório 'build'
      run: mkdir -p ./build

    - name: Salvando artefatos da compilacao api (bin)
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-api
        path: ./Gestor_Projetos_Tarefas.Api/bin/Release/net7.0

    - name: Salvando artefatos da compilacao testes
      uses: actions/upload-artifact@v2
      with:
        name:  artefatos-teste-build
        path: ./Gestor_Projetos_Tarefas.Api.Test/bin/Release/net7.0


  testar:
    runs-on: ubuntu-latest
    needs: compilar
    
    steps:

    - name: Clona Repositorio
      uses: actions/checkout@v2

    - name: Configura .NET na VM
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
    
    - name: Baixando Artefatos
      uses: actions/download-artifact@v2
      with:
        name: artefatos-teste-build
        path: ./testes/

    - name: Executa testes
      run: dotnet test ./testes/Gestor_Projetos_Tarefas.Api.Test.dll --configuration Release --no-restore

  gerar_assets:
    needs: [compilar,testar]
    runs-on: ubuntu-latest

    steps:

    - name: Baixando Artefatos
      uses: actions/download-artifact@v2
      with:
        name: artefatos-api
        path: ./deployed/

    - name: Construindo imagem Docker
      run: docker build -f ./src/Gestor_Projetos_Tarefas.Api/Dockerfile -t nome-da-imagem:latest ./deployed/

    - name: Salvando imagem Docker nos artefatos
      uses: actions/upload-artifact@v2
      with:
        name: artefatos-api
        path: ./deployed
        retention-days: 7